### ISSUE TITLE
i have some  issues about running evaluate

### ISSUE THREAD

**Issue by byew** [lenyabloko/SemEval2020#1]
IN def get_eval_report(),

 prediction = str(int(not bool(int(prediction))))
ValueError: invalid literal for int() with base 10: 'does anyone have any idea where on the new cipro website one can check if a company name exists/ does not exist on their database?'

What is the reason for this error in this code, I can't understand.
Thank you,I hope you will help if you have time

**Comment by lenyabloko** [comment]
Do you still have this issue? If I don't hear from you, I will close it.
